#!/bin/bash
CONFIG="/config/haproxy.cfg"

#Check Config change
while /sbin/setuser abc inotifywait -q -e create,delete,modify,attrib $CONFIG /etc/hosts; do
        if [ ! -z $(pidof haproxy) ]; then
                echo "Config changed... Restarting HAProxy PID:$(pidof haproxy) ..."
                sv restart haproxy
                echo "Restarted, new PID:$(pidof haproxy)."
        else
                echo "Error : Haproxy is not running, exited."
                break
        fi
done
