#!/usr/bin/with-contenv bash
CONFIG="/config/haproxy.cfg"

#Check Config change
while s6-setuidgid abc inotifywait -q -e create,delete,modify,attrib $CONFIG /etc/hosts
do
	if [ ! -z $(pidof haproxy) ]; then
                echo "[INFO] Config changed... Restarting HAProxy PID:$(pidof haproxy) ..."
                sv restart haproxy
                echo "[INFO] Restarted, new PID:$(pidof haproxy)."
        else
                echo "[ERROR] Haproxy is not running, exited."
                break
        fi
done
