#!/usr/bin/with-contenv bash
HAPROXY_CONF="haproxy.cfg"
DEFAULT_SSL_FOLDER="/config/ssl/default"

# Copy default haproxy config
[ ! -f /config/haproxy.cfg ] && cp /defaults/$HAPROXY_CONF /config/haproxy.cfg ||  echo "[WARN] Config file already exists."

# Manage LetsEncrypt folder
mkdir -p $DEFAULT_SSL_FOLDER /config/ssl/letsencrypt
rm -Rf /etc/letsencrypt
ln -s "/config/ssl/letsencrypt" "/etc/letsencrypt"

# Manage log folder
mkdir -p /config/log

# Fix permissions
chown -R abc.abc /config
